# Badge component
com.vaadin.experimental.badgeComponent=true
# Slider component
com.vaadin.experimental.sliderComponent=true
# Master Detail Layout component
com.vaadin.experimental.masterDetailLayoutComponent=true
# Copilot experimental features
com.vaadin.experimental.copilotExperimentalFeatures=true
